ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sc\soundcloud_project\downloader\views.py", line 19, in index
    subprocess.run(['youtube-dl', '-x', '--audio-format', 'mp3', song_url], check=True)
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1462, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
               ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 859, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType
INFO:django.utils.autoreload:D:\sc\soundcloud_project\downloader\views.py changed, reloading.
